apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: enhanced-entity-picker-test
  title: Enhanced Entity Picker Test
  description: Test template to compare original EntityPicker vs Enhanced EntityPicker functionality
spec:
  owner: backstage/maintainers
  type: test

  parameters:
    - title: "🔍 Entity Picker Comparison Test"
      description: "Compare original vs enhanced EntityPicker behavior side by side"
      properties:
        
        # Original EntityPicker (baseline)
        originalPicker:
          title: "1. Original EntityPicker"
          type: string
          description: "Standard Backstage EntityPicker - stores entity reference"
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: User
            allowArbitraryValues: false
        
        # Enhanced EntityPicker without formatting (should behave identically)
        enhancedBasic:
          title: "2. Enhanced EntityPicker (Basic Mode)"
          type: string
          description: "Enhanced version without displayFormat - should behave exactly like original"
          ui:field: EnhancedEntityPicker
          ui:options:
            catalogFilter:
              kind: User
            allowArbitraryValues: false
        
        # Enhanced EntityPicker with title formatting
        enhancedWithTitle:
          title: "3. Enhanced EntityPicker (Title Format)"
          type: string
          description: "Shows entity title instead of reference"
          ui:field: EnhancedEntityPicker
          ui:options:
            catalogFilter:
              kind: User
            allowArbitraryValues: false
            displayFormat: "{{ metadata.title }}"
            hiddenEntityRef: "enhancedWithTitleRef"
        
        # Enhanced EntityPicker with complex formatting
        enhancedWithTemplate:
          title: "4. Enhanced EntityPicker (Template Format)"
          type: string
          description: "Shows custom formatted display with email"
          ui:field: EnhancedEntityPicker
          ui:options:
            catalogFilter:
              kind: User
            allowArbitraryValues: false
            displayFormat: "📧 {{ metadata.title }} - {{ spec.profile.email }}"
            hiddenEntityRef: "enhancedWithTemplateRef"
        
        # Enhanced EntityPicker with fallback syntax
        enhancedWithFallback:
          title: "5. Enhanced EntityPicker (Fallback Format)"
          type: string
          description: "Uses fallback syntax: title || displayName || name"
          ui:field: EnhancedEntityPicker
          ui:options:
            catalogFilter:
              kind: User
            allowArbitraryValues: false
            displayFormat: "metadata.title || spec.profile.displayName || metadata.name"
            hiddenEntityRef: "enhancedWithFallbackRef"

    - title: "📋 Results Review"
      description: "Review what gets stored in each field"
      properties:
        reviewNote:
          title: "Expected Results"
          type: string
          description: |
            After selecting the same user in all fields above:
            
            1. originalPicker: "user:default/john.doe"
            2. enhancedBasic: "user:default/john.doe" (same as #1)
            3. enhancedWithTitle: "John Doe" (+ hidden field with entity ref)
            4. enhancedWithTemplate: "📧 John Doe - john@company.com" (+ hidden field)
            5. enhancedWithFallback: "John Doe" or fallback value (+ hidden field)
          ui:widget: textarea
          ui:options:
            rows: 8
          default: |
            Test Instructions:
            1. Select the same user in fields 1-5 above
            2. Click "Review" to see what values are stored
            3. Verify enhanced fields show human-readable values
            4. Check that hidden entity reference fields are populated
            5. Confirm enhanced basic mode works exactly like original

  steps:
    - id: debug
      name: Debug Output
      action: debug:log
      input:
        message: |
          Field Values Comparison:
          
          Original EntityPicker: ${{ parameters.originalPicker }}
          Enhanced Basic: ${{ parameters.enhancedBasic }}
          Enhanced Title: ${{ parameters.enhancedWithTitle }}
          Enhanced Template: ${{ parameters.enhancedWithTemplate }}
          Enhanced Fallback: ${{ parameters.enhancedWithFallback }}
          
          Hidden Entity References:
          Title Ref: ${{ parameters.enhancedWithTitleRef }}
          Template Ref: ${{ parameters.enhancedWithTemplateRef }}
          Fallback Ref: ${{ parameters.enhancedWithFallbackRef }}

  output:
    text:
      - title: Test Results
        content: |
          ## Enhanced EntityPicker Test Results
          
          **Original**: `${{ parameters.originalPicker }}`
          **Enhanced Basic**: `${{ parameters.enhancedBasic }}`
          **Enhanced Title**: `${{ parameters.enhancedWithTitle }}`
          **Enhanced Template**: `${{ parameters.enhancedWithTemplate }}`
          **Enhanced Fallback**: `${{ parameters.enhancedWithFallback }}`
          
          ### Hidden Entity References
          - Title Hidden: `${{ parameters.enhancedWithTitleRef }}`
          - Template Hidden: `${{ parameters.enhancedWithTemplateRef }}`
          - Fallback Hidden: `${{ parameters.enhancedWithFallbackRef }}`