apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: enhanced-entity-picker-test
  title: Enhanced Entity Picker Test
  description: Test template to compare original EntityPicker vs Enhanced EntityPicker functionality
spec:
  owner: backstage/maintainers
  type: test

  parameters:
    - title: "🔍 Entity Picker Comparison Test"
      description: "Compare original vs enhanced EntityPicker behavior side by side"
      properties:
        # Original EntityPicker (baseline)
        originalPicker:
          title: "1. Original EntityPicker"
          type: string
          description: "Standard Backstage EntityPicker - stores entity reference"
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: User
            allowArbitraryValues: false

        # Enhanced EntityPicker without formatting (should behave identically)
        enhancedBasic:
          title: "2. Enhanced EntityPicker (Basic Mode)"
          type: string
          description: "Enhanced version without displayFormat - should behave exactly like original"
          ui:field: EnhancedEntityPicker
          ui:options:
            catalogFilter:
              kind: User
            allowArbitraryValues: false

        # Enhanced EntityPicker with formatting
        enhancedWithTitle:
          title: "3. Enhanced EntityPicker User"
          type: string
          description: "Shows entity title instead of reference"
          ui:field: EnhancedEntityPicker
          ui:options:
            catalogFilter:
              kind: User
            allowArbitraryValues: false
            displayFormat: "name: {{ metadata.name }} - email: {{ spec.profile.email }}"
            hiddenEntityRef: "enhancedHiddenUser"
        enhancedHiddenUser:
          type: string
          ui:widget: hidden
          ui:backstage:
            review:
              show: false
        # Enhanced EntityPicker
        enhancedWithTemplate:
          title: "4. Enhanced EntityPicker Resource"
          type: string
          description: "Shows custom formatted display"
          ui:field: EnhancedEntityPicker
          ui:options:
            catalogFilter:
              kind: Resource
            allowArbitraryValues: false
            displayFormat: "📧 {{ metadata.account_id }}"
            hiddenEntityRef: "enhancedHiddenResource"
        enhancedHiddenResource:
          type: string
          ui:widget: hidden
          ui:backstage:
            review:
              show: false

        # Enhanced EntityPicker with fallback syntax
        enhancedWithFallback:
          title: "5. Enhanced EntityPicker (Fallback Format)"
          type: string
          description: "Uses fallback syntax"
          ui:field: EnhancedEntityPicker
          ui:options:
            catalogFilter:
              kind: System
            allowArbitraryValues: false
            displayFormat: "{{ metadata.title || metadata.annotations.overdue-review || spec.owner }}"
            hiddenEntityRef: "enhancedHiddenSystem"
        enhancedHiddenSystem:
          type: string
          ui:widget: hidden
          ui:backstage:
            review:
              show: false

  steps:
    - id: fetch-user
      name: Fetch user details
      action: catalog:fetch
      input:
        entityRef: "${{ parameters.enhancedHiddenUser }}"

    - id: debug
      name: Debug Output fetch user
      action: debug:log
      input:
        message: |
          Field Values:

          Original EntityPicker: ${{ parameters.originalPicker }}
          Enhanced Basic: ${{ parameters.enhancedBasic }}
          Enhanced User: ${{ parameters.enhancedUser }}
          Enhanced Resource: ${{ parameters.enhancedResource }}
          Enhanced Fallback System: ${{ parameters.enhancedWithFallback }}

          Hidden Entity References:
          HiddenUser: ${{ parameters.enhancedHiddenUser }}
          HiddenResource: ${{ parameters.enhancedHiddenResource }}
          HiddenSystem: ${{ parameters.enhancedHiddenSystem }}

          User details:
          Name: ${{ steps['fetch-user'].output.entity.metadata.name }}
          Email: ${{ steps['fetch-user'].output.entity.spec.profile.email }}
          Department: ${{ steps['fetch-user'].output.entity.spec.profile.department }}

  # output:
  #   text:
  #     - title: Test Results
  #       content: |
  #         ## Enhanced EntityPicker Test Results

  #         **Original**: `${{ parameters.originalPicker }}`
  #         **Enhanced Basic**: `${{ parameters.enhancedBasic }}`
  #         **Enhanced Title**: `${{ parameters.enhancedWithTitle }}`
  #         **Enhanced Template**: `${{ parameters.enhancedWithTemplate }}`
  #         **Enhanced Fallback**: `${{ parameters.enhancedWithFallback }}`

  #         ### Hidden Entity References
  #         - Title Hidden: `${{ parameters.enhancedWithTitleRef }}`
  #         - Template Hidden: `${{ parameters.enhancedWithTemplateRef }}`
  #         - Fallback Hidden: `${{ parameters.enhancedWithFallbackRef }}`
