apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: enhanced-entity-picker-demo
  title: Enhanced Entity Picker Demo
  description: Demonstrates the EnhancedEntityPicker with dynamic formatting
spec:
  owner: user:default/example-owner
  type: service
  parameters:
    - title: Basic Information
      required:
        - name
        - secondaryOwner
      properties:
        name:
          title: Name
          type: string
          description: Name of the component
        secondaryOwner:
          title: Secondary Owner
          type: string
          description: You will be primary owner, please choose a secondary owner
          ui:field: EnhancedEntityPicker
          ui:options:
            # You can customize this format however you want
            displayEntityFieldAfterFormatting: ${{ metadata.name }} (${{ spec.profile.email }}) - ${{ spec.profile.displayName || "" }}
            catalogFilter:
              kind: User

  steps:
    # First, log the raw value to see what we get
    - id: log-raw-value
      name: Log Raw Secondary Owner Value
      action: debug:log
      input:
        message: "Raw secondary owner value:"
        value: "${{ parameters.secondaryOwner }}"

    # Extract the entity reference from the combined value
    - id: extract-entity-ref
      name: Extract Entity Reference
      action: debug:log
      input:
        message: "Extracting entity reference:"
        # The combined value format is: displayValue:::entityRef
        # We can extract the entity reference part using string operations
        display_part: "${{ parameters.secondaryOwner | split(':::')[0] }}"
        entity_ref_part: "${{ parameters.secondaryOwner | split(':::')[1] }}"

    # If you need to fetch the full entity data, you would use:
    # - id: fetch-entity
    #   name: Fetch Entity Data
    #   action: catalog:fetch-entity
    #   input:
    #     entityRef: "${{ parameters.secondaryOwner | split(':::')[1] }}"

    # For now, just demonstrate what you would typically do with the entity reference
    - id: use-entity-ref
      name: Using Entity Reference
      action: debug:log
      input:
        message: "What you can do with the entity reference:"
        example_actions: |
          1. Fetch the complete entity data using catalog:fetch-entity
          2. Use the entity reference directly in ownership files
          3. Extract the parts (kind, namespace, name) for use in other steps

        # Example of extracting parts from the entity reference
        # Format is kind:namespace/name
        entity_parts: |
          Entity Reference: ${{ parameters.secondaryOwner | split(':::')[1] }}

          You could extract:
          - Kind: ${{ parameters.secondaryOwner | split(':::')[1] | split(':')[0] }}
          - Namespace/Name: ${{ parameters.secondaryOwner | split(':::')[1] | split(':')[1] }}
