apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-template
  title: Example Template with Enhanced Entity Picker
  description: Demonstrates the EnhancedEntityPicker
spec:
  owner: user:default/example-owner
  type: service
  parameters:
    - title: Basic Information
      required:
        - name
        - secondaryOwner
      properties:
        name:
          title: Name
          type: string
          description: Name of the component
        secondaryOwner:
          title: Secondary Owner
          type: string
          description: you will be primary owner, please choose a secondary owner
          ui:field: EnhancedEntityPicker
          ui:options:
            displayEntityFieldAfterFormatting: ${{ metadata.name }} (${{  spec.profile.email }} )
            catalogFilter:
              kind: User

    # Optional: For debugging during development
    # - title: Debug
    #   properties:
    #     debug:
    #       ui:field: DebugLog
    #       type: string

  steps:
    - id: fetch-info
      name: Fetch Information
      action: debug:log
      input:
        message: "Selected secondary owner: ${{ parameters.secondaryOwner }}"
        # Access specific entity properties (if using advanced version)
        # owner_name: "${{ parameters.secondaryOwner.__entity.metadata.name }}"
        # owner_email: "${{ parameters.secondaryOwner.__entity.spec.profile.email }}"
        # full_entity: "${{ parameters.secondaryOwner.__entity }}"

    # Your other template steps would follow
