# Working Template - No Auth Issues!

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: working-enhanced-entity-picker
  title: Working Enhanced Entity Picker
  description: Uses simple actions + built-in catalog:fetch
spec:
  owner: platform-team
  type: test

  parameters:
    - title: Test Entity Selection
      required:
        - testEntity
      properties:
        testEntity:
          title: Select Any Entity
          type: string
          ui:field: EnhancedEntityPicker
          ui:options:
            displayEntityFieldAfterFormatting: "${{ metadata.name }} [${{ kind }}]"
            catalogFilter:
              kind: User

  steps:
    - id: show-display-value
      name: Show Display Value
      action: debug:log
      input:
        message: |
          📋 SELECTED ENTITY:
          Display Value: ${{ parameters.testEntity }}

    # Step 1: Extract entity reference from display format (no catalog access needed)
    - id: extract-entity-ref
      name: Extract Entity Reference
      action: enhanced:extractEntityRef
      input:
        displayValue: ${{ parameters.testEntity }}
        displayTemplate: "${{ metadata.name }} [${{ kind }}]"
        entityKind: "User"
        entityNamespace: "default"

    - id: show-extracted-ref
      name: Show Extracted Reference
      action: debug:log
      input:
        message: |
          🔍 EXTRACTED:
          Entity Ref: ${{ steps['extract-entity-ref'].output.entityRef }}
          Entity Name: ${{ steps['extract-entity-ref'].output.extractedName }}

    # Step 2: Use built-in catalog:fetch (guaranteed to work with auth)
    - id: fetch-entity-data
      name: Fetch Entity Data
      action: catalog:fetch
      input:
        entityRef: ${{ steps['extract-entity-ref'].output.entityRef }}

    - id: show-full-entity-data
      name: Show Full Entity Data
      action: debug:log
      input:
        message: |
          🎯 COMPLETE ENTITY DATA:

          Display: ${{ parameters.testEntity }}
          EntityRef: ${{ steps['extract-entity-ref'].output.entityRef }}

          Full Entity Details:
          - Kind: ${{ steps['fetch-entity-data'].output.entity.kind }}
          - Name: ${{ steps['fetch-entity-data'].output.entity.metadata.name }}
          - Namespace: ${{ steps['fetch-entity-data'].output.entity.metadata.namespace }}
          - Email: ${{ steps['fetch-entity-data'].output.entity.spec.profile.email || 'N/A' }}
          - Department: ${{ steps['fetch-entity-data'].output.entity.spec.profile.department || 'N/A' }}
          - Description: ${{ steps['fetch-entity-data'].output.entity.metadata.description || 'N/A' }}

          🎉 SUCCESS! No auth issues!

    # Alternative: Extract email directly (if display format contains email)
    - id: extract-email
      name: Extract Email from Display
      action: enhanced:extractEmail
      input:
        displayValue: ${{ parameters.testEntity }}

    - id: show-extracted-email
      name: Show Extracted Email
      action: debug:log
      input:
        message: |
          📧 EMAIL EXTRACTION:
          Name: ${{ steps['extract-email'].output.name }}
          Email: ${{ steps['extract-email'].output.email }}
          Guessed EntityRef: ${{ steps['extract-email'].output.entityRef }}

    - id: create-test-file
      name: Create Test File
      action: fs:write
      input:
        path: ./entity-data.json
        content: |
          {
            "test": "enhanced-entity-picker-working",
            "userSelection": {
              "displayValue": "${{ parameters.testEntity }}",
              "extractedEntityRef": "${{ steps['extract-entity-ref'].output.entityRef }}",
              "extractedName": "${{ steps['extract-entity-ref'].output.extractedName }}"
            },
            "resolvedEntity": {
              "kind": "${{ steps['fetch-entity-data'].output.entity.kind }}",
              "name": "${{ steps['fetch-entity-data'].output.entity.metadata.name }}",
              "namespace": "${{ steps['fetch-entity-data'].output.entity.metadata.namespace }}",
              "email": "${{ steps['fetch-entity-data'].output.entity.spec.profile.email || null }}",
              "department": "${{ steps['fetch-entity-data'].output.entity.spec.profile.department || null }}"
            },
            "emailExtraction": {
              "name": "${{ steps['extract-email'].output.name }}",
              "email": "${{ steps['extract-email'].output.email }}"
            },
            "status": "success - no auth issues!"
          }
