# Simple Example - One Property Only

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-entity-picker-test
  title: Simple Entity Picker Test
  description: Test one property with clean display
spec:
  owner: platform-team
  type: example

  parameters:
    - title: Basic Setup
      required:
        - projectName
        - owner
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name of your project

        owner:
          title: Project Owner
          type: string
          description: Choose the project owner
          ui:field: EnhancedEntityPicker
          ui:options:
            displayEntityFieldAfterFormatting: "${{ metadata.name }} (${{ spec.profile.email }})"
            catalogFilter:
              kind: User

  steps:
    - id: show-clean-values
      name: Show Clean Values
      action: debug:log
      input:
        message: |
          ✅ WHAT USER SEES (Clean Format):
          Project Name: ${{ parameters.projectName }}
          Owner: ${{ parameters.owner }}

          🎯 FULL ENTITY DATA (Developer Access):
          Owner Name: ${{ parameters.owner_name }}
          Owner Email: ${{ parameters.owner_email }}
          Owner Department: ${{ parameters.owner_department }}
          Owner Entity Ref: ${{ parameters.owner_entityRef }}
          Owner Display Name: ${{ parameters.owner_displayName }}
