# Test template to verify your enhanced entity picker actions work

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-enhanced-entity-picker
  title: Test Enhanced Entity Picker
  description: Test the enhanced entity picker with custom actions
spec:
  owner: platform-team
  type: test

  parameters:
    - title: Test Entity Selection
      required:
        - testEntity
      properties:
        testEntity:
          title: Select Any Entity
          type: string
          description: Choose any entity to test with
          ui:field: EnhancedEntityPicker
          ui:options:
            displayEntityFieldAfterFormatting: "${{ metadata.name }} [${{ kind }}]"
            catalogFilter:
              kind: User # Change this to test different entity types

  steps:
    - id: show-display-value
      name: Show Display Value
      action: debug:log
      input:
        message: |
          📋 CLEAN DISPLAY VALUE:
          Selected Entity: ${{ parameters.testEntity }}

    - id: resolve-entity
      name: Resolve Entity Data
      action: enhanced:resolveEntity
      input:
        displayValue: ${{ parameters.testEntity }}
        displayTemplate: "${{ metadata.name }} [${{ kind }}]"
        catalogFilter:
          kind: User

    - id: debug-entity-properties
      name: Debug Entity Properties
      action: enhanced:debugEntity
      input:
        entity: ${{ steps['resolve-entity'].output.entity }}

    - id: show-resolved-data
      name: Show Resolved Data
      action: debug:log
      input:
        message: |
          🎯 RESOLVED ENTITY DATA:

          EntityRef: ${{ steps['resolve-entity'].output.entityRef }}
          Kind: ${{ steps['resolve-entity'].output.entity.kind }}
          Name: ${{ steps['resolve-entity'].output.entity.metadata.name }}
          Namespace: ${{ steps['resolve-entity'].output.entity.metadata.namespace || 'default' }}

          # Check debug logs above to see ALL available properties!

    - id: create-test-file
      name: Create Test File
      action: fs:write
      input:
        path: ./test-results.json
        content: |
          {
            "test": "enhanced-entity-picker",
            "displayValue": "${{ parameters.testEntity }}",
            "resolvedEntity": {
              "entityRef": "${{ steps['resolve-entity'].output.entityRef }}",
              "kind": "${{ steps['resolve-entity'].output.entity.kind }}",
              "name": "${{ steps['resolve-entity'].output.entity.metadata.name }}",
              "namespace": "${{ steps['resolve-entity'].output.entity.metadata.namespace || 'default' }}"
            },
            "status": "success"
          }
