# Simple Example - One Property Only

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-entity-picker-test
  title: Simple Entity Picker Test
  description: Test one property with clean display
spec:
  owner: platform-team
  type: example

  parameters:
    - title: Basic Setup
      required:
        - projectName
        - owner
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name of your project

        owner:
          title: Project Owner
          type: string
          description: Choose the project owner
          ui:field: EnhancedEntityPicker
          ui:options:
            displayEntityFieldAfterFormatting: "${{ metadata.name }} (${{ spec.profile.email }})"
            catalogFilter:
              kind: User

  steps:
    - id: show-what-we-got
      name: Show What We Got
      action: debug:log
      input:
        message: |
          📋 SIMPLE TEST RESULTS:

          Project Name: ${{ parameters.projectName }}
          Owner (what form stores): ${{ parameters.owner }}

    - id: resolve-owner-data
      name: Resolve Owner Data
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.owner }}

    - id: show-resolved-data
      name: Show Resolved Data
      action: debug:log
      input:
        message: |
          🎯 RESOLVED ENTITY DATA:

          Owner Name: ${{ steps['resolve-owner-data'].output.entity.metadata.name }}
          Owner Email: ${{ steps['resolve-owner-data'].output.entity.spec.profile.email }}
          Owner Department: ${{ steps['resolve-owner-data'].output.entity.spec.profile.department || 'Unknown' }}

    - id: create-simple-file
      name: Create Simple File
      action: fs:write
      input:
        path: ./project-info.txt
        content: |
          Project: ${{ parameters.projectName }}
          Owner: ${{ steps['resolve-owner-data'].output.entity.metadata.name }}
          Email: ${{ steps['resolve-owner-data'].output.entity.spec.profile.email }}
          Entity Reference: ${{ parameters.owner }}
