# Fixed YAML - Requires metadata.name in template + dynamic entity kind

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fixed-enhanced-entity-picker
  title: Fixed Enhanced Entity Picker
  description: Properly extracts metadata.name and gets entity kind dynamically
spec:
  owner: platform-team
  type: test

  parameters:
    - title: Select Entity
      required:
        - selectedEntity
      properties:
        selectedEntity:
          title: Choose User
          type: string
          ui:field: EnhancedEntityPicker
          ui:options:
            # FIXED: Template MUST include metadata.name for accurate entity reference
            displayEntityFieldAfterFormatting: "${{ metadata.name }} - ${{ metadata.title }} - ${{ spec.profile.department }}"
            catalogFilter:
              kind: User # This will be extracted dynamically

  steps:
    # STEP 1: Extract entity reference using metadata.name (guaranteed to exist)
    - id: extract-reference
      name: Extract Entity Reference
      action: enhanced:resolveEntity
      input:
        displayValue: ${{ parameters.selectedEntity }}
        displayTemplate: "${{ metadata.name }} - ${{ metadata.title }} - ${{ spec.profile.department }}"
        catalogFilter: # Pass the entire filter to extract entity kind
          kind: User
        entityNamespace: "default"

    # STEP 2: Use built-in catalog:fetch with the REAL entity name
    - id: fetch-entity
      name: Fetch Entity Data
      action: catalog:fetch
      input:
        entityRef: ${{ steps['extract-reference'].output.entityRef }}

    # RESULT: Show that we have accurate entity resolution
    - id: show-result
      name: Show Result
      action: debug:log
      input:
        message: |
          ✅ SUCCESS! Accurate Entity Resolution:

          👤 User Sees: ${{ parameters.selectedEntity }}
          📝 Example: "jdoe - John Doe - Engineering"

          🎯 Extracted Data:
          - Real Entity Name: ${{ steps['extract-reference'].output.extractedName }}
          - Entity Kind: ${{ steps['extract-reference'].output.entityKind }}
          - Entity Reference: ${{ steps['extract-reference'].output.entityRef }}

          📋 Full Entity Data:
          - Name: ${{ steps['fetch-entity'].output.entity.metadata.name }}
          - Title: ${{ steps['fetch-entity'].output.entity.metadata.title || 'N/A' }}
          - Department: ${{ steps['fetch-entity'].output.entity.spec.profile.department || 'N/A' }}
          - Email: ${{ steps['fetch-entity'].output.entity.spec.profile.email || 'N/A' }}

          🎉 Perfect! Now using REAL entity names, not guessed ones!
