# Fixed YAML - Use enhanced:resolveEntity instead of extraction

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: working-enhanced-entity-picker-fixed
  title: Working Enhanced Entity Picker - FIXED
  description: Uses enhanced:resolveEntity action for composite display formats
spec:
  owner: platform-team
  type: test

  parameters:
    - title: Test Entity Selection
      required:
        - testEntity
      properties:
        testEntity:
          title: Select Any Entity
          type: string
          ui:field: EnhancedEntityPicker
          ui:options:
            displayEntityFieldAfterFormatting: "${{ metadata.title }} - ${{ spec.profile.department }}"
            catalogFilter:
              kind: User

  steps:
    - id: show-display-value
      name: Show Display Value
      action: debug:log
      input:
        message: |
          📋 SELECTED ENTITY:
          Display Value: ${{ parameters.testEntity }}

    # FIXED: Use enhanced:resolveEntity with MATCHING template
    - id: resolve-entity
      name: Resolve Entity Data
      action: enhanced:resolveEntity
      input:
        displayValue: ${{ parameters.testEntity }}
        displayTemplate: "${{ metadata.title }} - ${{ spec.profile.department }}"
        catalogFilter:
          kind: User

    - id: show-resolved-data
      name: Show Resolved Data
      action: debug:log
      input:
        message: |
          🎯 RESOLVED ENTITY DATA:

          Display: ${{ parameters.testEntity }}
          EntityRef: ${{ steps['resolve-entity'].output.entityRef }}

          Full Entity Details:
          - Kind: ${{ steps['resolve-entity'].output.entity.kind }}
          - Name: ${{ steps['resolve-entity'].output.entity.metadata.name }}
          - Title: ${{ steps['resolve-entity'].output.entity.metadata.title }}
          - Department: ${{ steps['resolve-entity'].output.entity.spec.profile.department }}
          - Email: ${{ steps['resolve-entity'].output.entity.spec.profile.email || 'N/A' }}
          - Description: ${{ steps['resolve-entity'].output.entity.metadata.description || 'N/A' }}

          ✅ SUCCESS! Found the exact entity by matching display format!

    - id: debug-entity-properties
      name: Debug Entity Properties
      action: enhanced:debugEntity
      input:
        entity: ${{ steps['resolve-entity'].output.entity }}

    - id: create-test-file
      name: Create Test File
      action: fs:write
      input:
        path: ./entity-data.json
        content: |
          {
            "test": "enhanced-entity-picker-fixed",
            "userSelection": {
              "displayValue": "${{ parameters.testEntity }}",
              "resolvedEntityRef": "${{ steps['resolve-entity'].output.entityRef }}"
            },
            "resolvedEntity": {
              "kind": "${{ steps['resolve-entity'].output.entity.kind }}",
              "name": "${{ steps['resolve-entity'].output.entity.metadata.name }}",
              "title": "${{ steps['resolve-entity'].output.entity.metadata.title }}",
              "department": "${{ steps['resolve-entity'].output.entity.spec.profile.department }}",
              "email": "${{ steps['resolve-entity'].output.entity.spec.profile.email || null }}"
            },
            "status": "success - proper entity resolution!"
          }
