# Debug YAML - Extensive logging to troubleshoot 401 issues

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: working-enhanced-entity-picker-debug
  title: Working Enhanced Entity Picker - DEBUG VERSION
  description: Extensive logging to troubleshoot authentication issues
spec:
  owner: platform-team
  type: test

  parameters:
    - title: Test Entity Selection
      required:
        - testEntity
      properties:
        testEntity:
          title: Select Any Entity
          type: string
          ui:field: EnhancedEntityPicker
          ui:options:
            displayEntityFieldAfterFormatting: "${{ metadata.title }} - ${{ spec.profile.department }}"
            catalogFilter:
              kind: User

  steps:
    - id: show-display-value
      name: Show Display Value
      action: debug:log
      input:
        message: |
          📋 SELECTED ENTITY:
          Display Value: ${{ parameters.testEntity }}

          🔍 About to attempt entity resolution...
          This will show detailed logs about the HTTP request and response.

    # DEBUG VERSION: This will show extensive logs
    - id: resolve-entity-debug
      name: Resolve Entity Data (Debug)
      action: enhanced:resolveEntity
      input:
        displayValue: ${{ parameters.testEntity }}
        displayTemplate: "${{ metadata.title }} - ${{ spec.profile.department }}"
        catalogFilter:
          kind: User

    - id: show-resolved-data
      name: Show Resolved Data
      action: debug:log
      input:
        message: |
          🎯 RESOLVED ENTITY DATA:

          Display: ${{ parameters.testEntity }}
          EntityRef: ${{ steps['resolve-entity-debug'].output.entityRef }}

          Full Entity Details:
          - Kind: ${{ steps['resolve-entity-debug'].output.entity.kind }}
          - Name: ${{ steps['resolve-entity-debug'].output.entity.metadata.name }}
          - Title: ${{ steps['resolve-entity-debug'].output.entity.metadata.title }}
          - Department: ${{ steps['resolve-entity-debug'].output.entity.spec.profile.department }}
          - Email: ${{ steps['resolve-entity-debug'].output.entity.spec.profile.email || 'N/A' }}
          - Description: ${{ steps['resolve-entity-debug'].output.entity.metadata.description || 'N/A' }}

          ✅ SUCCESS! Debugging approach worked!

    - id: debug-entity-properties
      name: Debug Entity Properties
      action: enhanced:debugEntity
      input:
        entity: ${{ steps['resolve-entity-debug'].output.entity }}

    - id: create-test-file
      name: Create Test File
      action: fs:write
      input:
        path: ./entity-data-debug.json
        content: |
          {
            "test": "enhanced-entity-picker-debug",
            "userSelection": {
              "displayValue": "${{ parameters.testEntity }}",
              "resolvedEntityRef": "${{ steps['resolve-entity-debug'].output.entityRef }}"
            },
            "resolvedEntity": {
              "kind": "${{ steps['resolve-entity-debug'].output.entity.kind }}",
              "name": "${{ steps['resolve-entity-debug'].output.entity.metadata.name }}",
              "title": "${{ steps['resolve-entity-debug'].output.entity.metadata.title }}",
              "department": "${{ steps['resolve-entity-debug'].output.entity.spec.profile.department }}",
              "email": "${{ steps['resolve-entity-debug'].output.entity.spec.profile.email || null }}"
            },
            "status": "success - debug version worked!"
          }
