apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-compute
  title: Provision ROSA Compute Application
  description: Build a ROSA compute application
  tags: [compute, rosa, merna]
spec:
  owner: wg119310
  type: service
  
  parameters:
    - title: Create New ROSA Application
      required:
        - logicalGroup
        - name
      properties:
        logicalGroup:
          title: Logical group
          type: string
          description: The logical group where the cache will be created
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - kind: System
                spec.type: logical-group
            
        name:
          title: Application Name
          type: string
          description: Test app names must match prod app names. If using lanes/envs, plan to match your pre-prod app name with the prod app name
          pattern: '^(?!kube-|openshift-|aws-|open-cluster-management-)[a-zA-Z][a-zA-Z0-9-]*$'
          
        sourceRepoId:
          title: Existing Source Repository ID
          type: string
          description: Migrating or already have an existing repository, enter ID here. If not a base source code repository will be created for you.
          pattern: '^[0-9]+

        # Configuration checkboxes
        appType:
          title: Java
          type: boolean
          description: ROSA automation will cater changes specific to the app type
          default: false
          
        createConfigMap:
          title: Create Config Map
          type: boolean
          description: Create a config map file typically used for external properties or config
          default: false
          
        internetEnabled:
          title: Internet Enabled
          type: boolean
          description: Make your app accessible from the public internet, B2C or B2B applications
          default: false

      dependencies:
        internetEnabled:
          oneOf:
            - properties:
                internetEnabled:
                  const: false
            - properties:
                internetEnabled:
                  const: true
                cidrsToAllowAccessFrom:
                  title: CIDRs to allow access from
                  type: string
                  description: Restrict internet access to your app via specific IP addresses or CIDR ranges
        
        sourceRepoId:
          oneOf:
            - properties:
                sourceRepoId:
                  const: ""
            - properties:
                sourceRepoId:
                  minLength: 1
                existingSourceBranchName:
                  title: Existing Source Branch Name
                  type: string
                  description: Enter an existing branch name for the ROSA automation to source from; otherwise, the default branch will be used if none is provided
                  
                skipExistingFileUpdates:
                  title: Skip existing file updates
                  type: boolean
                  default: false

        hiddenField:
          type: string
          ui:field: GetEntraUserOauth
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              optional: true
              scopes:
                - api://ifc/user

  steps:
    - id: fetch-logical-group
      name: Fetching logical group entity...
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.logicalGroup }}

    - id: create-compute
      name: Creating compute infrastructure...
      action: cloud-experience:compute:create
      input:
        businessApplicationId: ${{ steps['fetch-logical-group'].output.entity.metadata.annotations['solms-id'] }}
        environment: TEST
        name: ${{ parameters.name }}
        sourceRepoId: ${{ parameters.sourceRepoId }}
        appType: ${{ parameters.appType }}
        createConfigMap: ${{ parameters.createConfigMap }}
        internetEnabled: ${{ parameters.internetEnabled }}
        cidrsToAllowAccessFrom: ${{ parameters.cidrsToAllowAccessFrom }}
        existingSourceBranchName: ${{ parameters.existingSourceBranchName }}
        skipExistingFileUpdates: ${{ parameters.skipExistingFileUpdates }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

  output:
    links:
      - title: Compute Application Details
        content: |
          **Your ROSA Compute Application has been created successfully!**
          
          - **Name:** ${{ steps['create-compute'].output.name }}
          - **Environment:** TEST
          - **Logical Group:** ${{ parameters.logicalGroup }}
          - **Source Repository:** ${{ parameters.sourceRepoId || 'Auto-generated' }}
          
          **Configuration:**
          - Java Application: ${{ parameters.appType ? 'Yes' : 'No' }}
          - Config Map: ${{ parameters.createConfigMap ? 'Enabled' : 'Disabled' }}
          - Internet Access: ${{ parameters.internetEnabled ? 'Enabled' : 'Disabled' }}
          
          **Your MERNA Compute has begun its provisioning process!**
          
          _Provisioning typically takes **5+ minutes** to complete._
          
          📋 [**View ${{ parameters.name }}**] in logical group ${{ parameters.logicalGroup }}

          ui:help: 'Repository ID must be a number'

        # Configuration checkboxes
        appType:
          title: Java
          type: boolean
          description: ROSA automation will cater changes specific to the app type
          default: false
          
        createConfigMap:
          title: Create Config Map
          type: boolean
          description: Create a config map file typically used for external properties or config
          default: false
          
        internetEnabled:
          title: Internet Enabled
          type: boolean
          description: Make your app accessible from the public internet, B2C or B2B applications
          default: false

        # GitLab Automation fields (conditional)
        existingSourceBranchName:
          title: Existing Source Branch Name
          type: string
          description: Enter an existing branch name for the ROSA automation to source from; otherwise, the default branch will be used if none is provided
          ui:field: ConditionalField
          ui:fieldCondition: 
            property: sourceRepoId
            when: 
              isNot: ""
          
        skipExistingFileUpdates:
          title: Skip existing file updates
          type: boolean
          default: false
          ui:field: ConditionalField
          ui:fieldCondition: 
            property: sourceRepoId
            when: 
              isNot: ""

        hiddenField:
          type: string
          ui:field: GetEntraUserOauth
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              optional: true
              scopes:
                - api://ifc/user

  steps:
    - id: fetch-logical-group
      name: Fetching logical group entity...
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.logicalGroup }}

    - id: create-compute
      name: Creating compute infrastructure...
      action: cloud-experience:compute:create
      input:
        businessApplicationId: ${{ steps['fetch-logical-group'].output.entity.metadata.annotations['solms-id'] }}
        environment: TEST
        name: ${{ parameters.name }}
        sourceRepoId: ${{ parameters.sourceRepoId }}
        appType: ${{ parameters.appType }}
        createConfigMap: ${{ parameters.createConfigMap }}
        internetEnabled: ${{ parameters.internetEnabled }}
        existingSourceBranchName: ${{ parameters.existingSourceBranchName }}
        skipExistingFileUpdates: ${{ parameters.skipExistingFileUpdates }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

  output:
    links:
      - title: Compute Application Details
        content: |
          **Your ROSA Compute Application has been created successfully!**
          
          - **Name:** ${{ steps['create-compute'].output.name }}
          - **Environment:** TEST
          - **Logical Group:** ${{ parameters.logicalGroup }}
          - **Source Repository:** ${{ parameters.sourceRepoId || 'Auto-generated' }}
          
          **Configuration:**
          - Java Application: ${{ parameters.appType ? 'Yes' : 'No' }}
          - Config Map: ${{ parameters.createConfigMap ? 'Enabled' : 'Disabled' }}
          - Internet Access: ${{ parameters.internetEnabled ? 'Enabled' : 'Disabled' }}
          
          **Your MERNA Compute has begun its provisioning process!**
          
          _Provisioning typically takes **5+ minutes** to complete._
          
          📋 [**View ${{ parameters.name }}**] in logical group ${{ parameters.logicalGroup }}

          >>>>>>>>
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-compute
  title: Provision ROSA Compute Application
  description: Build a ROSA compute application
  tags: [compute, rosa, merna]
spec:
  owner: wg119310
  type: service
  
  parameters:
    - title: Create New ROSA Application
      required:
        - logicalGroup
        - name
      properties:
        logicalGroup:
          title: Logical group
          type: string
          description: The logical group where the cache will be created
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - kind: System
                spec.type: logical-group
            
        name:
          title: Application Name
          type: string
          description: Test app names must match prod app names. If using lanes/envs, plan to match your pre-prod app name with the prod app name
          pattern: '^(?!kube-|openshift-|aws-|open-cluster-management-)[a-zA-Z][a-zA-Z0-9-]*$'
          errorMessage:
            pattern: 'Does not start with "kube-", "openshift-", "aws-", or "open-cluster-management-", has no consecutive hyphens, starts with a letter, and is alphanumeric'
          
        sourceRepoId:
          title: Existing Source Repository ID
          type: string
          description: Migrating or already have an existing repository, enter ID here. If not a base source code repository will be created for you.
          pattern: '^[0-9]*$'
          errorMessage:
            pattern: 'Repository ID must be a number'
          ui:options:
            validateOnBlur: true

        appType:
          title: Java
          type: boolean
          description: ROSA automation will cater changes specific to the app type
          default: false
          
        createConfigMap:
          title: Create Config Map
          type: boolean
          description: Create a config map file typically used for external properties or config
          default: false
          
        internetEnabled:
          title: Internet Enabled
          type: boolean
          description: Make your app accessible from the public internet, B2C or B2B applications
          default: false

        hiddenField:
          type: string
          ui:field: GetEntraUserOauth
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              optional: true
              scopes:
                - api://ifc/user

      dependencies:
        internetEnabled:
          oneOf:
            - properties:
                internetEnabled:
                  enum: [false]
            - properties:
                internetEnabled:
                  enum: [true]
                cidrsToAllowAccessFrom:
                  title: CIDRs to allow access from
                  type: string
                  description: Restrict internet access to your app via specific IP addresses or CIDR ranges
        
        sourceRepoId:
          oneOf:
            - properties:
                sourceRepoId:
                  enum: [""]
            - properties:
                sourceRepoId:
                  not:
                    enum: [""]
                existingSourceBranchName:
                  title: Existing Source Branch Name
                  type: string
                  description: Enter an existing branch name for the ROSA automation to source from; otherwise, the default branch will be used if none is provided
                  
                skipExistingFileUpdates:
                  title: Skip existing file updates
                  type: boolean
                  default: false

  steps:
    - id: fetch-logical-group
      name: Fetching logical group entity...
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.logicalGroup }}

    - id: create-compute
      name: Creating compute infrastructure...
      action: cloud-experience:compute:create
      input:
        businessApplicationId: ${{ steps['fetch-logical-group'].output.entity.metadata.annotations['solms-id'] }}
        environment: TEST
        name: ${{ parameters.name }}
        sourceRepoId: ${{ parameters.sourceRepoId }}
        appType: ${{ parameters.appType }}
        createConfigMap: ${{ parameters.createConfigMap }}
        internetEnabled: ${{ parameters.internetEnabled }}
        cidrsToAllowAccessFrom: ${{ parameters.cidrsToAllowAccessFrom }}
        existingSourceBranchName: ${{ parameters.existingSourceBranchName }}
        skipExistingFileUpdates: ${{ parameters.skipExistingFileUpdates }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

  output:
    links:
      - title: Compute Application Details
        content: |
          **Your ROSA Compute Application has been created successfully!**
          
          - **Name:** ${{ steps['create-compute'].output.name }}
          - **Environment:** TEST
          - **Logical Group:** ${{ parameters.logicalGroup }}
          - **Source Repository:** ${{ parameters.sourceRepoId || 'Auto-generated' }}
          
          **Configuration:**
          - Java Application: ${{ parameters.appType ? 'Yes' : 'No' }}
          - Config Map: ${{ parameters.createConfigMap ? 'Enabled' : 'Disabled' }}
          - Internet Access: ${{ parameters.internetEnabled ? 'Enabled' : 'Disabled' }}
          
          **Your MERNA Compute has begun its provisioning process!**
          
          _Provisioning typically takes **5+ minutes** to complete._
          
          📋 [**View ${{ parameters.name }}**] in logical group ${{ parameters.logicalGroup }}