apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-compute
  title: Provision ROSA Compute Application
  description: Build a ROSA compute application
  tags: [compute, rosa, infrastructure]
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Create New ROSA Application
      required:
        - name
      properties:
        name:
          title: Application Name
          type: string
          description: Test app names must match prod app names. If using lanes/envs, plan to match your pre-prod app name with the prod app name
          pattern: "^(?!kube-|openshift-|aws-|open-cluster-management-)[a-zA-Z][a-zA-Z0-9-]*$"

        sourceRepoId:
          title: Existing Source Repository ID
          type: string
          description: Migrating or already have an existing repository, enter ID here. If not a base source code repository will be created for you.

        # Configuration checkboxes
        java:
          title: Java
          type: boolean
          description: ROSA automation will cater changes specific to the app type
          default: false

        createConfigMap:
          title: Create Config Map
          type: boolean
          description: Create a config map file typically used for external properties or config
          default: false

        internetEnabled:
          title: Internet Enabled
          type: boolean
          description: Make your app accessible from the public internet, B2C or B2B applications
          default: false

        # GitLab Automation fields (conditional)
        existingSourceBranchName:
          title: Existing Source Branch Name
          type: string
          description: Enter an existing branch name for the ROSA automation to source from; otherwise, the default branch will be used if none is provided
          ui:field: ConditionalField
          ui:fieldCondition:
            property: sourceRepoId
            when:
              isNot: ""

        skipExistingFileUpdates:
          title: Skip existing file updates
          type: boolean
          default: false
          ui:field: ConditionalField
          ui:fieldCondition:
            property: sourceRepoId
            when:
              isNot: ""

    - title: Authentication
      properties:
        hiddenField:
          type: string
          ui:field: GetEntraUserOauth
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              optional: true
              scopes:
                - api://ifc/user

  steps:
    - id: create-compute
      name: Creating compute infrastructure...
      action: cloud-experience:compute:create
      input:
        name: ${{ parameters.name }}
        sourceRepoId: ${{ parameters.sourceRepoId }}
        java: ${{ parameters.java }}
        createConfigMap: ${{ parameters.createConfigMap }}
        internetEnabled: ${{ parameters.internetEnabled }}
        existingSourceBranchName: ${{ parameters.existingSourceBranchName }}
        skipExistingFileUpdates: ${{ parameters.skipExistingFileUpdates }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

  output:
    links:
      - title: Compute Application Details
        content: |
          **Your ROSA Compute Application has been created successfully!**

          - **Name:** ${{ steps['create-compute'].output.name }}
          - **Environment:** TEST
          - **Source Repository:** ${{ parameters.sourceRepoId || 'Auto-generated' }}

          **Configuration:**
          - Java Application: ${{ parameters.java ? 'Yes' : 'No' }}
          - Config Map: ${{ parameters.createConfigMap ? 'Enabled' : 'Disabled' }}
          - Internet Access: ${{ parameters.internetEnabled ? 'Enabled' : 'Disabled' }}
